export const FETCH_ALL_SERIES_SUCCESS = 'FETCH_ALL_SERIES_SUCCESS';
export const FETCH_ALL_SERIES_FAILURE = 'FETCH_ALL_SERIES_FAILURE';
export const FETCH_ALL_SERIES_REQUEST = 'FETCH_ALL_SERIES_REQUEST';

export const FETCH_SERIES_BY_ID_SUCCESS = 'FETCH_SERIES_BY_ID_SUCCESS';
export const FETCH_SERIES_BY_ID_FAILURE = 'FETCH_SERIES_BY_ID_FAILURE';
export const FETCH_SERIES_BY_ID_REQUEST = 'FETCH_SERIES_BY_ID_REQUEST';

export const INCREASE_SERIES_OFFSET = 'INCREASE_SERIES_OFFSET';
export const SET_SERIES_TO_NULL = 'SET_SERIES_TO_NULL';
