export const FETCH_ALL_CHARACTERS_SUCCESS = 'FETCH_ALL_CHARACTERS_SUCCESS';
export const FETCH_ALL_CHARACTERS_FAILURE = 'FETCH_ALL_CHARACTERS_FAILURE';
export const FETCH_ALL_CHARACTERS_REQUEST = 'FETCH_ALL_CHARACTERS_REQUEST';

export const FETCH_ALL_COMICS_SUCCESS = 'FETCH_ALL_COMICS_SUCCESS';
export const FETCH_ALL_COMICS_FAILURE = 'FETCH_ALL_COMICS_FAILURE';
export const FETCH_ALL_COMICS_REQUEST = 'FETCH_ALL_COMICS_REQUEST';

export const FETCH_ALL_SERIES_SUCCESS = 'FETCH_ALL_SERIES_SUCCESS';
export const FETCH_ALL_SERIES_FAILURE = 'FETCH_ALL_SERIES_FAILURE';
export const FETCH_ALL_SERIES_REQUEST = 'FETCH_ALL_SERIES_REQUEST';

export const FETCH_ALL_EVENTS_SUCCESS = 'FETCH_ALL_EVENTS_SUCCESS';
export const FETCH_ALL_EVENTS_FAILURE = 'FETCH_ALL_EVENTS_FAILURE';
export const FETCH_ALL_EVENTS_REQUEST = 'FETCH_ALL_EVENTS_REQUEST';

export const FETCH_CHARACTER_BY_ID_SUCCESS = 'FETCH_CHARACTER_BY_ID_SUCCESS';
export const FETCH_CHARACTER_BY_ID_FAILURE = 'FETCH_CHARACTER_BY_ID_FAILURE';
export const FETCH_CHARACTER_BY_ID_REQUEST = 'FETCH_CHARACTER_BY_ID_REQUEST';

export const FETCH_COMICS_BY_ID_SUCCESS = 'FETCH_COMICS_BY_ID_SUCCESS';
export const FETCH_COMICS_BY_ID_FAILURE = 'FETCH_COMICS_BY_ID_FAILURE';
export const FETCH_COMICS_BY_ID_REQUEST = 'FETCH_COMICS_BY_ID_REQUEST';

export const FETCH_SERIES_BY_ID_SUCCESS = 'FETCH_SERIES_BY_ID_SUCCESS';
export const FETCH_SERIES_BY_ID_FAILURE = 'FETCH_SERIES_BY_ID_FAILURE';
export const FETCH_SERIES_BY_ID_REQUEST = 'FETCH_SERIES_BY_ID_REQUEST';

export const FETCH_EVENT_BY_ID_SUCCESS = 'FETCH_EVENT_BY_ID_SUCCESS';
export const FETCH_EVENT_BY_ID_FAILURE = 'FETCH_EVENT_BY_ID_FAILURE';
export const FETCH_EVENT_BY_ID_REQUEST = 'FETCH_EVENT_BY_ID_REQUEST';

export const SEARCH_CHARACTER_BY_NAME_SUCCESS =
  'SEARCH_CHARACTER_BY_NAME_SUCCESS';
export const SEARCH_CHARACTER_BY_NAME_FAILURE =
  'SEARCH_CHARACTER_BY_NAME_FAILURE';
export const SEARCH_CHARACTER_BY_NAME_REQUEST =
  'SEARCH_CHARACTER_BY_NAME_REQUEST';

export const SEARCH_COMICS_BY_TITLE_SUCCESS = 'SEARCH_COMICS_BY_TITLE_SUCCESS';
export const SEARCH_COMICS_BY_TITLE_FAILURE = 'SEARCH_COMICS_BY_TITLE_FAILURE';
export const SEARCH_COMICS_BY_TITLE_REQUEST = 'SEARCH_COMICS_BY_TITLE_REQUEST';

export const INCREASE_CHARACTERS_OFFSET = 'INCREASE_CHARACTERS_OFFSET';
export const INCREASE_COMICS_OFFSET = 'INCREASE_COMICS_OFFSET';
export const INCREASE_SERIES_OFFSET = 'INCREASE_SERIES_OFFSET';
export const INCREASE_EVENTS_OFFSET = 'INCREASE_EVENTS_OFFSET';

export const SET_FAVORITE_CHARACTERS = 'SET_FAVORITE_CHARACTERS';

export const SET_ITEMS_TO_NULL = 'SET_ITEMS_TO_NULL';

export const GET_CURRENT_USER = 'GET_CURRENT_USER';
