export const FETCH_ALL_CHARACTERS_SUCCESS = 'FETCH_ALL_CHARACTERS_SUCCESS';
export const FETCH_ALL_CHARACTERS_FAILURE = 'FETCH_ALL_CHARACTERS_FAILURE';
export const FETCH_ALL_CHARACTERS_REQUEST = 'FETCH_ALL_CHARACTERS_REQUEST';

export const FETCH_ALL_COMICS_SUCCESS = 'FETCH_ALL_COMICS_SUCCESS';
export const FETCH_ALL_COMICS_FAILURE = 'FETCH_ALL_COMICS_FAILURE';
export const FETCH_ALL_COMICS_REQUEST = 'FETCH_ALL_COMICS_REQUEST';

export const FETCH_CHARACTER_BY_ID_SUCCESS = 'FETCH_CHARACTER_BY_ID_SUCCESS';
export const FETCH_CHARACTER_BY_ID_FAILURE = 'FETCH_CHARACTER_BY_ID_FAILURE';
export const FETCH_CHARACTER_BY_ID_REQUEST = 'FETCH_CHARACTER_BY_ID_REQUEST';

export const SEARCH_CHARACTER_BY_NAME_SUCCESS =
  'SEARCH_CHARACTER_BY_NAME_SUCCESS';
export const SEARCH_CHARACTER_BY_NAME_FAILURE =
  'SEARCH_CHARACTER_BY_NAME_FAILURE';
export const SEARCH_CHARACTER_BY_NAME_REQUEST =
  'SEARCH_CHARACTER_BY_NAME_REQUEST';

export const INCREASE_OFFSET = 'INCREASE_OFFSET';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
