export const FETCH_ALL_COMICS_SUCCESS = 'FETCH_ALL_COMICS_SUCCESS';
export const FETCH_ALL_COMICS_FAILURE = 'FETCH_ALL_COMICS_FAILURE';
export const FETCH_ALL_COMICS_REQUEST = 'FETCH_ALL_COMICS_REQUEST';

export const FETCH_COMICS_BY_ID_SUCCESS = 'FETCH_COMICS_BY_ID_SUCCESS';
export const FETCH_COMICS_BY_ID_FAILURE = 'FETCH_COMICS_BY_ID_FAILURE';
export const FETCH_COMICS_BY_ID_REQUEST = 'FETCH_COMICS_BY_ID_REQUEST';

export const INCREASE_COMICS_OFFSET = 'INCREASE_COMICS_OFFSET';
export const SET_COMICS_TO_NULL = 'SET_COMICS_TO_NULL';
