export const FETCH_ALL_EVENTS_SUCCESS = 'FETCH_ALL_EVENTS_SUCCESS';
export const FETCH_ALL_EVENTS_FAILURE = 'FETCH_ALL_EVENTS_FAILURE';
export const FETCH_ALL_EVENTS_REQUEST = 'FETCH_ALL_EVENTS_REQUEST';

export const FETCH_EVENT_BY_ID_SUCCESS = 'FETCH_EVENT_BY_ID_SUCCESS';
export const FETCH_EVENT_BY_ID_FAILURE = 'FETCH_EVENT_BY_ID_FAILURE';
export const FETCH_EVENT_BY_ID_REQUEST = 'FETCH_EVENT_BY_ID_REQUEST';

export const INCREASE_EVENTS_OFFSET = 'INCREASE_EVENTS_OFFSET';
export const SET_EVENTS_TO_NULL = 'SET_EVENTS_TO_NULL';
